Added TITLE_DEFAULT option to rearrenge the title Update resolutions on pair with pkg/models/resolution.go Fixed missing suffix="." on performer Fixed the issue that prevent using the script more than once in a row: TAG_SETS[key].add(tag["name"]) AttributeError: 'list' object has no attribute 'add'